package com.poc.dynamo.model;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.NoArgsConstructor;
import lombok.ToString;

@ToString
@NoArgsConstructor
@DynamoDBTable(tableName = "emp-info-prod")
public class EmpInfo implements Serializable {

	private static final long serialVersionUID = 114499593148812364L;
	private String empId;
	private String empName;
	private String address;
	private boolean isActive;

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getEmpId() {
		return empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@DynamoDBAttribute
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@DynamoDBAttribute
	public boolean isActive() {
		return isActive;
	}

	public void setActive(boolean isActive) {
		this.isActive = isActive;
	}

	@DynamoDBAttribute
	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	public EmpInfo(String empName, String address, boolean isActive) {
		super();
		this.empName = empName;
		this.address = address;
		this.isActive = isActive;
	}

}
